included:
  - GitMenuBar
  - GitMenuBarTests

excluded:
  - build
  - .xcode-build
  - .xcode-build-tests
  - dist

line_length:
  warning: 140
  error: 260

type_body_length:
  warning: 500
  error: 600

file_length:
  warning: 425
  error: 450

function_body_length:
  warning: 80
  error: 120

identifier_name:
  min_length: 2

opening_brace:
  severity: warning

reporter: "xcode"
