included:
  - GitMenuBar
  - GitMenuBarTests

excluded:
  - build
  - .xcode-build
  - .xcode-build-tests
  - dist

line_length:
  warning: 140
  error: 260

type_body_length:
  warning: 1400
  error: 2000

file_length:
  warning: 1800
  error: 2500

function_body_length:
  warning: 80
  error: 120

identifier_name:
  min_length: 2

reporter: "xcode"
