@testable import GitMenuBar
import XCTest

final class CommitMessagePolicyTests: XCTestCase {
    private let policy = CommitMessagePolicy.shared

    func testStripsHarnessPollutionAndKeepsConventionalCommitSubject() {
        let input = """
        feat: add endpoint

        Generated by Cursor
        """

        switch policy.sanitize(input) {
        case let .success(sanitized):
            XCTAssertEqual(sanitized, "feat: add endpoint")
        case let .failure(error):
            XCTFail("Expected acceptance, got \(error)")
        }
    }

    func testRejectsWhenOnlyPollutionRemains() {
        let input = """
        Generated by Codex

        Co-authored-by: Cursor <noreply@cursor.com>
        """

        switch policy.sanitize(input) {
        case .success:
            XCTFail("Expected rejection when only pollution remains")
        case let .failure(error):
            XCTAssertEqual(error, .emptyAfterSanitization)
        }
    }

    func testKeepsAllowlistedSignedOffByTrailer() {
        let input = """
        fix: handle edge case

        Signed-off-by: Ada Lovelace <ada@example.com>
        """

        switch policy.sanitize(input) {
        case let .success(sanitized):
            XCTAssertTrue(sanitized.contains("Signed-off-by: Ada Lovelace <ada@example.com>"))
            XCTAssertTrue(sanitized.hasPrefix("fix: handle edge case"))
        case let .failure(error):
            XCTFail("Expected acceptance, got \(error)")
        }
    }

    func testStripsHarnessCoAuthorButKeepsHumanCoAuthor() {
        let input = """
        feat: pair commit

        Co-authored-by: Cursor <noreply@cursor.com>
        Co-authored-by: Grace Hopper <grace@example.com>
        """

        switch policy.sanitize(input) {
        case let .success(sanitized):
            XCTAssertFalse(sanitized.localizedCaseInsensitiveContains("cursor"))
            XCTAssertTrue(sanitized.contains("Co-authored-by: Grace Hopper <grace@example.com>"))
        case let .failure(error):
            XCTFail("Expected acceptance, got \(error)")
        }
    }

    func testGenerateCommitMessageStripsHarnessPollutionFromProvider() async throws {
        let session = makeMockedURLSession()
        MockURLProtocol.requestHandler = { request in
            let response = """
            {"choices":[{"message":{"content":"feat: add widget\\n\\nGenerated by Cursor"}}]}
            """
            let data = response.data(using: .utf8) ?? Data()
            return (
                HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!,
                data
            )
        }

        let service = AICommitMessageService(session: session)

        let message = try await service.generateCommitMessage(
            provider: makeProvider(),
            apiKey: "secret",
            model: "gpt-4.1",
            rawDiff: sampleDiff,
            scopeDescription: "Selected commit"
        )

        XCTAssertEqual(message, "feat: add widget")
    }

    func testGenerateCommitMessageRejectsWhenProviderReturnsOnlyPollution() async {
        let session = makeMockedURLSession()
        MockURLProtocol.requestHandler = { request in
            let response = """
            {"choices":[{"message":{"content":"Generated by Cursor"}}]}
            """
            let data = response.data(using: .utf8) ?? Data()
            return (
                HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!,
                data
            )
        }

        let service = AICommitMessageService(session: session)

        do {
            _ = try await service.generateCommitMessage(
                provider: makeProvider(),
                apiKey: "secret",
                model: "gpt-4.1",
                rawDiff: sampleDiff,
                scopeDescription: "Selected commit"
            )
            XCTFail("Expected Message policy rejection")
        } catch let error as AIError {
            guard case let .messagePolicyRejected(message) = error else {
                return XCTFail("Unexpected AIError: \(error)")
            }
            XCTAssertTrue(message.contains("Message policy"))
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }
}

@MainActor
final class GitMenuBarCommitSessionTests: XCTestCase {
    func testReadinessIsFalseWithoutProviderKeyAndModel() {
        let providerStore = AIProviderStore(dataStore: InMemoryAIProviderStoreDataStore())
        let session = GitMenuBarCommitSession(
            repositoryPath: "/tmp",
            providerStore: providerStore,
            keychainStore: InMemoryAIAPIKeyStore(),
            messageService: AICommitMessageService()
        )

        XCTAssertFalse(session.isReadyForGeneration)
        XCTAssertEqual(
            session.generationDisabledReason,
            "Configure at least one AI provider in Settings to enable commit generation."
        )
    }

    func testReadinessIsTrueWithProviderKeyAndModel() {
        let providerStore = AIProviderStore(dataStore: InMemoryAIProviderStoreDataStore())
        let provider = AIProviderConfig(
            name: "OpenAI",
            type: .openAI,
            endpointURL: "https://api.openai.com",
            selectedModel: "gpt-4.1",
            availableModels: ["gpt-4.1"],
            hasStoredAPIKey: true
        )
        providerStore.upsertProvider(provider)

        let session = GitMenuBarCommitSession(
            repositoryPath: "/tmp",
            providerStore: providerStore,
            keychainStore: InMemoryAIAPIKeyStore(storage: [provider.id: "secret-key"]),
            messageService: AICommitMessageService()
        )

        XCTAssertTrue(session.isReadyForGeneration)
        XCTAssertEqual(session.generationDisabledReason, "")
    }

    func testResolveGitRootFromRepositoryPathScope() throws {
        let repoURL = try createTemporaryGitRepository(testName: #function)
        let resolved = try GitMenuBarCommitSession.resolveGitRoot(
            from: repoURL.path,
            using: GitCommandRunner()
        )
        XCTAssertEqual(
            URL(fileURLWithPath: resolved, isDirectory: true).standardizedFileURL.path,
            repoURL.standardizedFileURL.path
        )
    }
}

private func makeProvider() -> AIProviderConfig {
    AIProviderConfig(
        name: "OpenAI",
        type: .openAI,
        endpointURL: "https://api.openai.com",
        selectedModel: "gpt-4.1",
        availableModels: ["gpt-4.1"],
        hasStoredAPIKey: true
    )
}

private let sampleDiff = """
diff --git a/README.md b/README.md
--- a/README.md
+++ b/README.md
@@ -1 +1,2 @@
 base
+updated
"""
