@testable import GitMenuBar
import XCTest

final class CompanionCLIServiceTests: XCTestCase {
    private let service = CompanionCLIService()
    private let policy = CommitMessagePolicy.shared

    func testSanitizedMessageRejectsHarnessPollutionWithPolicyExitCode() {
        let input = """
        Generated by Cursor

        Co-authored-by: Cursor <noreply@cursor.com>
        """

        do {
            _ = try service.sanitizedMessage(input, policy: policy)
            XCTFail("Expected policy rejection")
        } catch let error as CompanionCLIService.Error {
            XCTAssertEqual(error.exitCode, .policyRejected)
            XCTAssertEqual(error.cliExitCode, CompanionCLIExitCode.policyRejected.rawValue)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }

    func testSanitizedMessageAcceptsConventionalCommit() throws {
        let message = try service.sanitizedMessage("feat: add CLI", policy: policy)
        XCTAssertEqual(message, "feat: add CLI")
    }

    func testMakeSessionRejectsNonGitDirectory() {
        let options = CompanionCLIScopeOptions(
            repositoryPathScope: "/tmp",
            staged: false,
            all: false,
            outputFormat: .json,
            messageOverride: nil
        )

        do {
            _ = try service.makeSession(options: options)
            XCTFail("Expected invalid repository")
        } catch let error as CompanionCLIService.Error {
            XCTAssertEqual(error.exitCode, .invalidRepository)
            XCTAssertEqual(error.cliExitCode, CompanionCLIExitCode.invalidRepository.rawValue)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }

    func testResolveMessageWithOverrideDoesNotRequireAIReadiness() async throws {
        let providerStore = AIProviderStore(dataStore: InMemoryAIProviderStoreDataStore())
        let session = GitMenuBarCommitSession(
            repositoryPath: "/tmp",
            providerStore: providerStore,
            keychainStore: InMemoryAIAPIKeyStore(),
            messageService: AICommitMessageService()
        )

        let options = CompanionCLIScopeOptions(
            repositoryPathScope: "/tmp",
            staged: false,
            all: false,
            outputFormat: .json,
            messageOverride: "feat: manual message"
        )

        let message = try await service.resolveMessage(session: session, options: options)
        XCTAssertEqual(message, "feat: manual message")
    }

    func testMessageResultJSONIncludesSchemaVersion() throws {
        let payload = CompanionCLIMessageResult(message: "feat: test")
        let json = try CompanionCLIEncoder.encodeJSON(payload)
        XCTAssertTrue(json.contains("\"schemaVersion\":1"))
        XCTAssertTrue(json.contains("\"message\":\"feat: test\""))
    }

    func testAssertIndexUnlockedFailsWhenLockPresent() throws {
        let repoURL = try createTemporaryGitRepository(testName: #function)
        let lockURL = repoURL.appendingPathComponent(".git/index.lock")
        FileManager.default.createFile(atPath: lockURL.path, contents: Data("lock".utf8))

        defer {
            try? FileManager.default.removeItem(at: lockURL)
        }

        do {
            try service.assertIndexUnlocked(at: repoURL.path)
            XCTFail("Expected index lock refusal")
        } catch let error as CompanionCLIService.Error {
            XCTAssertEqual(error.cliExitCode, CompanionCLIExitCode.operationalFailure)
        }
    }

    func testScopeOptionsResolveStagedAndAllFlags() {
        let staged = CompanionCLIScopeOptions(
            repositoryPathScope: ".",
            staged: true,
            all: false,
            outputFormat: .json,
            messageOverride: nil
        )
        XCTAssertEqual(staged.resolvedDiffScope(), DiffScope.staged.rawValue)

        let all = CompanionCLIScopeOptions(
            repositoryPathScope: ".",
            staged: false,
            all: true,
            outputFormat: .plain,
            messageOverride: nil
        )
        XCTAssertEqual(all.resolvedDiffScope(), DiffScope.all.rawValue)
    }
}

private extension CompanionCLIService.Error {
    var cliExitCode: Int32 {
        switch self {
        case .indexLocked, .operational:
            return CompanionCLIExitCode.operationalFailure
        default:
            return exitCode.rawValue
        }
    }
}
