@testable import GitMenuBar
import XCTest

@MainActor
final class MainMenuActionCoordinatorTests: XCTestCase {
    private var defaults: UserDefaults!
    private var suiteName = ""

    override func setUp() {
        super.setUp()
        suiteName = "MainMenuActionCoordinatorTests-\(UUID().uuidString)"
        defaults = UserDefaults(suiteName: suiteName)
        defaults.removePersistentDomain(forName: suiteName)
    }

    override func tearDown() {
        MockURLProtocol.requestHandler = nil
        defaults?.removePersistentDomain(forName: suiteName)
        defaults = nil
        suiteName = ""
        super.tearDown()
    }

    func testPerformCommitUsesManualMessageWithoutInvokingAI() async throws {
        let repoURL = try createTemporaryGitRepository(testName: #function)
        let fileURL = repoURL.appendingPathComponent("README.md")
        try "base\nmanual-change\n".write(to: fileURL, atomically: true, encoding: .utf8)

        let gitManager = GitManager(repositoryPathOverride: repoURL.path)
        await waitForWorkingTreeUpdate(gitManager)

        let providerStore = AIProviderStore(defaults: defaults)
        let apiKeyStore = SpyAIAPIKeyStore()
        let actionCoordinator = makeActionCoordinator(
            gitManager: gitManager,
            providerStore: providerStore,
            apiKeyStore: apiKeyStore,
            session: makeMockedURLSession()
        )

        let result = await actionCoordinator.performCommit(commentText: "feat: manual commit")

        XCTAssertEqual(result, .committed)
        XCTAssertEqual(apiKeyStore.readCount, 0)
        XCTAssertNil(actionCoordinator.alert)

        let headMessage = try runGit(["log", "-1", "--pretty=%B"], in: repoURL)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        XCTAssertEqual(headMessage, "feat: manual commit")
    }

    func testPerformCommitGeneratesMessageWhenInputIsEmpty() async throws {
        let repoURL = try createTemporaryGitRepository(testName: #function)
        let fileURL = repoURL.appendingPathComponent("README.md")
        try "base\nauto-change\n".write(to: fileURL, atomically: true, encoding: .utf8)

        let gitManager = GitManager(repositoryPathOverride: repoURL.path)
        await waitForWorkingTreeUpdate(gitManager)

        let providerStore = AIProviderStore(defaults: defaults)
        let provider = AIProviderConfig(
            name: "OpenAI",
            type: .openAI,
            endpointURL: "https://mock.openai.local",
            selectedModel: "gpt-4.1"
        )
        providerStore.upsertProvider(provider)

        let apiKeyStore = InMemoryAIAPIKeyStore()
        apiKeyStore.saveAPIKey("test-key", for: provider.id)

        MockURLProtocol.requestHandler = { request in
            let response = "{\"choices\":[{\"message\":{\"content\":\"feat: generated by ai\"}}]}"
            let data = response.data(using: .utf8) ?? Data()
            return (
                HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!,
                data
            )
        }

        let actionCoordinator = makeActionCoordinator(
            gitManager: gitManager,
            providerStore: providerStore,
            apiKeyStore: apiKeyStore,
            session: makeMockedURLSession()
        )

        let result = await actionCoordinator.performCommit(commentText: "")

        XCTAssertEqual(result, .committed)
        XCTAssertNil(actionCoordinator.alert)

        let headMessage = try runGit(["log", "-1", "--pretty=%B"], in: repoURL)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        XCTAssertEqual(headMessage, "feat: generated by ai")
    }

    func testPerformSyncOpensOptionsWhenRemoteIsAhead() async throws {
        let repoURL = try createTemporaryGitRepository(testName: #function)
        let gitManager = GitManager(repositoryPathOverride: repoURL.path)
        await waitForWorkingTreeUpdate(gitManager)
        gitManager.isRemoteAhead = true
        gitManager.isAheadOfRemote = true

        let actionCoordinator = makeActionCoordinator(
            gitManager: gitManager,
            providerStore: AIProviderStore(defaults: defaults),
            apiKeyStore: InMemoryAIAPIKeyStore(),
            session: makeMockedURLSession()
        )

        let result = await actionCoordinator.performSync()

        XCTAssertEqual(result, .requiresOptions)
        XCTAssertTrue(actionCoordinator.showSyncOptions)
    }

    func testPerformCommitAndPushOpensSyncOptionsWhenRemoteIsAhead() async throws {
        let remoteDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("GitMenuBarTests")
            .appendingPathComponent(#function + "-" + UUID().uuidString)
        try FileManager.default.createDirectory(at: remoteDirectory, withIntermediateDirectories: true)

        let remoteURL = remoteDirectory.appendingPathComponent("origin.git")
        try runGit(["init", "--bare", remoteURL.path], in: remoteDirectory)

        let localRepoURL = try createTemporaryGitRepository(testName: #function + "-local")
        try runGit(["remote", "add", "origin", remoteURL.path], in: localRepoURL)
        try runGit(["push", "-u", "origin", "HEAD"], in: localRepoURL)

        let peerCloneURL = remoteDirectory.appendingPathComponent("peer")
        try runGit(["clone", remoteURL.path, peerCloneURL.path], in: remoteDirectory)
        try runGit(["config", "user.email", "test@example.com"], in: peerCloneURL)
        try runGit(["config", "user.name", "GitMenuBar Tests"], in: peerCloneURL)

        let peerFileURL = peerCloneURL.appendingPathComponent("REMOTE.md")
        try "remote advance\n".write(to: peerFileURL, atomically: true, encoding: .utf8)
        try runGit(["add", "REMOTE.md"], in: peerCloneURL)
        try runGit(["commit", "-m", "feat: remote advance"], in: peerCloneURL)
        try runGit(["push"], in: peerCloneURL)

        let localFileURL = localRepoURL.appendingPathComponent("README.md")
        try "base\nlocal commit needed\n".write(to: localFileURL, atomically: true, encoding: .utf8)

        let gitManager = GitManager(repositoryPathOverride: localRepoURL.path)
        await waitForWorkingTreeUpdate(gitManager)

        let providerStore = AIProviderStore(defaults: defaults)
        let provider = AIProviderConfig(
            name: "OpenAI",
            type: .openAI,
            endpointURL: "https://mock.openai.local",
            selectedModel: "gpt-4.1"
        )
        providerStore.upsertProvider(provider)

        let apiKeyStore = InMemoryAIAPIKeyStore()
        apiKeyStore.saveAPIKey("test-key", for: provider.id)

        MockURLProtocol.requestHandler = { request in
            let response = "{\"choices\":[{\"message\":{\"content\":\"feat: local generated\"}}]}"
            let data = response.data(using: .utf8) ?? Data()
            return (
                HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!,
                data
            )
        }

        let actionCoordinator = makeActionCoordinator(
            gitManager: gitManager,
            providerStore: providerStore,
            apiKeyStore: apiKeyStore,
            session: makeMockedURLSession()
        )

        let result = await actionCoordinator.performCommit(
            commentText: "",
            shouldPushAfterCommit: true
        )

        XCTAssertEqual(result, .committedAndNeedsSyncOptions)
        XCTAssertTrue(actionCoordinator.showSyncOptions)
        XCTAssertNil(actionCoordinator.alert)
    }

    private func makeActionCoordinator(
        gitManager: GitManager,
        providerStore: AIProviderStore,
        apiKeyStore: any AIAPIKeyStore,
        session: URLSession
    ) -> MainMenuActionCoordinator {
        let aiCoordinator = AICommitCoordinator(
            providerStore: providerStore,
            keychainStore: apiKeyStore,
            messageService: AICommitMessageService(session: session),
            gitManager: gitManager
        )

        return MainMenuActionCoordinator(
            gitManager: gitManager,
            aiCommitCoordinator: aiCoordinator
        )
    }

    private func waitForWorkingTreeUpdate(_ gitManager: GitManager, timeout: TimeInterval = 3) async {
        let expectation = expectation(description: "working tree refresh")
        gitManager.updateUncommittedFiles {
            expectation.fulfill()
        }
        await fulfillment(of: [expectation], timeout: timeout)
    }
}

private final class SpyAIAPIKeyStore: AIAPIKeyStore {
    private var storage: [UUID: String]

    private(set) var readCount = 0

    init(storage: [UUID: String] = [:]) {
        self.storage = storage
    }

    func saveAPIKey(_ apiKey: String, for providerId: UUID) {
        storage[providerId] = apiKey
    }

    func apiKey(for providerId: UUID) -> String? {
        readCount += 1
        return storage[providerId]
    }

    func fetchAllAPIKeys() -> [UUID: String] {
        storage
    }

    func deleteAPIKey(for providerId: UUID) {
        storage.removeValue(forKey: providerId)
    }
}
