import Foundation

/// Product-owned **Message policy** shared by the menu bar app and Companion CLI.
///
/// Sanitizes commit message text and rejects **harness authorship pollution**
/// (forced attribution injected by agent harnesses) while preserving intentional
/// trailers such as `Signed-off-by:`.
enum CommitMessagePolicyError: Error, Equatable, LocalizedError {
    case emptyAfterSanitization

    var errorDescription: String? {
        switch self {
        case .emptyAfterSanitization:
            "Commit message is empty after applying Message policy."
        }
    }
}

struct CommitMessagePolicy: Sendable {
    static let shared = CommitMessagePolicy()

    /// Built-in denylist for harness authorship pollution.
    ///
    /// - Lines that attribute generation to a harness (`Generated by …`, `Created with …`).
    /// - `Co-authored-by:` trailers naming known harness identities (Cursor, Codex, Copilot, etc.)
    ///   or harness email domains (for example `noreply@cursor.com`).
    private static let harnessCoAuthorPattern: NSRegularExpression = {
        let harnessName = """
        (?:cursor|codex|(?:github\\s+)?copilot|openai|anthropic|chatgpt|harness)
        """
        let harnessEmailOrDomain = """
        (?:\
        noreply@(?:cursor|openai|anthropic)\\.com\
        |[^@\\s]+@(?:cursor|openai|anthropic)\\.com\
        |(?:cursor|openai|anthropic)\\.com\
        )
        """
        let pattern = """
        ^\\s*Co-authored-by:\\s*(?:\
        \(harnessName)\\b\
        |.*<[^>]*\(harnessEmailOrDomain)[^>]*>\
        )
        """
        guard let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) else {
            preconditionFailure("Invalid harness Co-authored-by Message policy pattern")
        }
        return regex
    }()

    private static let generatedByPattern: NSRegularExpression = {
        let pattern = #"^\s*(?:Generated by|Created with)\b"#
        guard let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) else {
            preconditionFailure("Invalid Generated-by Message policy pattern")
        }
        return regex
    }()

    /// Intentional trailers that must survive sanitization.
    private static let allowlistedTrailerPrefixes = [
        "Signed-off-by:"
    ]

    func sanitize(_ message: String) -> Result<String, CommitMessagePolicyError> {
        let normalized = message
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")

        var keptLines: [String] = []

        for line in normalized.components(separatedBy: "\n") {
            if isAllowlistedTrailer(line) {
                keptLines.append(line)
                continue
            }

            if isHarnessPollution(line) {
                continue
            }

            keptLines.append(line)
        }

        let sanitized = trimTrailingBlankLines(from: keptLines)
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        guard !sanitized.isEmpty else {
            return .failure(.emptyAfterSanitization)
        }

        return .success(sanitized)
    }

    private func isAllowlistedTrailer(_ line: String) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        return Self.allowlistedTrailerPrefixes.contains { trimmed.hasPrefix($0) }
    }

    private func isHarnessPollution(_ line: String) -> Bool {
        let range = NSRange(line.startIndex ..< line.endIndex, in: line)
        if Self.generatedByPattern.firstMatch(in: line, options: [], range: range) != nil {
            return true
        }
        if Self.harnessCoAuthorPattern.firstMatch(in: line, options: [], range: range) != nil {
            return true
        }
        return false
    }

    private func trimTrailingBlankLines(from lines: [String]) -> [String] {
        var result = lines
        while let last = result.last,
              last.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        {
            result.removeLast()
        }
        return result
    }
}

extension CommitMessagePolicyError {
    var aiError: AIError {
        switch self {
        case .emptyAfterSanitization:
            .messagePolicyRejected(
                "Commit message is empty after applying Message policy."
            )
        }
    }
}
